MVC5-Seneca/Controllers/HfedEmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Castle.Core.Internal;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MVC5_Seneca.DataAccessLayer;
using MVC5_Seneca.EntityModels;
using MVC5_Seneca.ViewModels;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace MVC5_Seneca.Controllers
{
    public class HfedEmailController : Controller
    {
        private readonly SenecaContext db = new SenecaContext();

        // GET: HfedEmail/Index
        public ActionResult Index(HfedEmailViewModel email)
        {
            if (email != null)
            {
                TempData.Keep();
                email.Recipients = TempData["Recipients"] as List<HfedEmailRecipient>;    
            
                // Convert to HfedEmail (for different requests to all use Index, a different name of model is needed.)
                HfedEmail model = new HfedEmail()
                {
                    Title = email.Title,
                    EmailText = email.EmailText,
                    HtmlContent =email .HtmlContent, 
                    Recipients = email.Recipients
                }; 
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "HfedSchedules");
            }
        }

        // POST: HfedEmail/Index
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include ="Title,EmailText,Recipients")] HfedEmail hfedEmail )
        {
            if (hfedEmail != null)
            {
                foreach (HfedEmailRecipient recipient in hfedEmail.Recipients)
                {
                    if (recipient.Checked)
                    {
                        var text = "<p>";
                        text += hfedEmail.EmailText.Replace(Environment.NewLine, "</p><p>");
                        text += "</p>";
                        DateTime startDate = Convert.ToDateTime(Session["StartDate"]);
                        DateTime endDate = Convert.ToDateTime(Session["EndDate"]);
                        switch (hfedEmail.Title)
                        {
                            case "Email Drivers - Show Schedule with Driver Names":
                                 hfedEmail.HtmlContent = GetDriverSchedule(true, startDate, endDate);
                                break;
                            case "Email Drivers - Show Schedule with No Driver Names":
                                hfedEmail.HtmlContent = GetDriverSchedule(false, startDate, endDate);
                                break;
                            case "Email Reminders":
                                var reminderDate = Convert.ToDateTime(Session["ReminderDate"]);
                                hfedEmail.HtmlContent = GetReminderSchedule(reminderDate);
                                break;
                            case "Email Staff - Request Schedules":
                                hfedEmail.HtmlContent = GetTentativeSchedule();
                                break;
                        }
                        text += hfedEmail.HtmlContent;
                        SendEmail(recipient.Email, text);
                    }
                }
            }

            return RedirectToAction("Index", "HfedSchedules");
        }

        // GET: HfedEmail
        public ActionResult EmailStaffAsk()
        {
            var email = new HfedEmailViewModel();
            
            email.Title = "Email Staff - Request Schedules";
            var text = "Greetings MCCH HFED Team!\n";      
            text += " The HFED coordinator has tentatively copied the food delivery" +
                           " schedules from the past month into next month.\n Please sign in to the HFED" +
                           " website at MVC5Seneca.Azurewebsites.net to verify the details including" +
                           " the list of clients.";
                email.EmailText = text;

            var allUsers = db.Users.ToList();
            List<ApplicationUser> recipients = new List<ApplicationUser>();
            foreach (ApplicationUser user in allUsers)
            {
                if (UserIsInRole(user, "HfedStaff") || UserIsInRole(user,"HfedCoordinator"))
                {
                    recipients.Add(user);                
                }
            }                                                                                  
            
            var newList = new List<HfedEmailRecipient>();
            foreach (ApplicationUser user in recipients)
            {
                newList.Add(new HfedEmailRecipient() 
                    { Id = user.Id, FullName = user.FullName, Email = user.Email, Checked =true});
            }

            email.HtmlContent = GetTentativeSchedule();
            TempData["Recipients"] = newList; // TempData holds complex data not passed in Redirects.                            
            email.Recipients = newList;                          

            return RedirectToAction( "Index", email);
        }  
        
        public ActionResult  EmailDriversAsk()
        {
            TempData["WithDrivers"] = false;
            EmailDrivers();
            return RedirectToAction("EmailDrivers", false);
        }

        public ActionResult EmailDriversShow()
        {
            TempData["WithDrivers"] = true;
            EmailDrivers();
            return RedirectToAction("EmailDrivers", true);
        }

        public ActionResult  EmailDrivers()    // Ask drivers for availability / show with drivers
        {
            bool withDrivers = (bool) (TempData["WithDrivers"]);
            var email = new HfedEmailViewModel
            {
                Title = "Email Drivers - "
            };
            if (withDrivers)
            {
                email.Title += "Show Schedule with Driver Names";
            }
            else
            {
                email.Title += "Show Schedule with No Driver Names";
            }
            var text = "Greetings Team!\n";
            if (withDrivers)
            {
                text += "Thank you for being a part of the team that works to allow ";
                text += "our MCCH residents to have Healthy Food Every Day.\n ";
            }
            else
            {
                text += "Please take a look and let us know which food runs you are ";
                text += "available for and interested in doing. ";
                text += "We will get back to you soon to confirm.\n";
            }
            
            if (!withDrivers)
            {
                text += "Thank you for helping people have Healthy Food Every Day!";
            }

            email.EmailText = text;
            var startDate = Convert.ToDateTime(Session["StartDate"]);
            var endDate = Convert.ToDateTime(Session["EndDate"]);
            email.HtmlContent = GetDriverSchedule(withDrivers,startDate ,endDate );
            var allUsers = db.Users.ToList();
            List<ApplicationUser> recipients = new List<ApplicationUser>();
            foreach (ApplicationUser user in allUsers)
            {
                if (UserIsInRole(user, "HfedDriver") || UserIsInRole(user, "HfedCoordinator"))
                {
                    recipients.Add(user);
                }
            }

            var newList = new List<HfedEmailRecipient>();
            foreach (ApplicationUser user in recipients)
            {
                newList.Add(new HfedEmailRecipient()
                    { Id = user.Id, FullName = user.FullName, Email = user.Email, Checked = true });
            }

            TempData["Recipients"] = newList; // TempData holds complex data not passed in Redirects.                            
            email.Recipients = newList;    
            return RedirectToAction("Index", email);  
        }

        public ActionResult EmailReminder(string reminderDate)
        {
            var email = new HfedEmailViewModel
            {
                Title = "Email Reminders"
            };
            var text = "Reminder:\n";
            text += "You have an upcoming HFED delivery:\n ";
            email.EmailText = text;

            if (Session["ReminderDate"] == null)
            {
                Session["ReminderDate"] = DateTime.Today.AddDays(2);
            }
            else
            {
                if (!reminderDate.IsNullOrEmpty())
                {
                    Session["ReminderDate"] = reminderDate;
                }
            }
                  
            DateTime dtReminderDate = Convert.ToDateTime(Session["ReminderDate"]);
            email.HtmlContent = GetReminderSchedule(dtReminderDate);

            GetReminderRecipients(Session["ReminderDate"].ToString()); // Puts Email Rrecipient list in TempData
            TempData.Keep();
            email.Recipients = TempData["Recipients"] as List<HfedEmailRecipient>;

            return RedirectToAction("Index", email);
        }
       
        // Send individual email
        private async void SendEmail(string address, string htmlContent)
        {
            var apiKey = Properties.Settings.Default.HFEDSendGridClient;
            var client = new SendGridClient(apiKey);
            var msg = new SendGridMessage()
            {
                From = new EmailAddress("Admin@SenecaHeightsEducationProgram.org", "HFED Coordinator"),
                Subject =("Healthy Food Every Day -  Schedule"),
                HtmlContent = htmlContent,                          
            };
            msg.AddTo(new EmailAddress(address, "HFED Team Member"));
            var unused = await client.SendEmailAsync(msg);    
        }

        private static string GetDriverSchedule(bool withDrivers, DateTime startDate, DateTime endDate)
        {
            using (var context = new SenecaContext())
            {

MVC5-Seneca/Views/HfedSchedules/Edit.cshtml
@model MVC5_Seneca.ViewModels.HfedScheduleViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <link rel="stylesheet" href="~/Content/themes/base/jquery-ui.min.css" /> @*// for date-picker*@
    @*Put page javascript in a separate .js file where breaks can be set during debugging:*@
    <script src="@Url.Content("/Scripts/HfedFunctions.js")"></script>
    <script src="~/Scripts/chosen.jquery.min.js"></script>
    <link href="~/Content/chosen.min.css" rel="stylesheet" />
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div>
        <h4>Edit HFED Food Run</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id) 
        <table>
            <tr>
                <td style="text-align:right">
                    <strong>@Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "col-md-2" }) </strong>
                </td>
                <td>
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", style = "width:75px" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td style="text-align: right">
                    <strong>PickUp Time</strong>
                </td>
                <td>
                    @Html.EditorFor(model => model.PickUpTime, new { htmlAttributes = new { @class = "form-control", style = "width:75px" } })
                    @Html.ValidationMessageFor(model => model.PickUpTime, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td>
                    <strong>@Html.LabelFor(m => m.Provider, new { @class = "col-md-2" })</strong>
                </td>
                <td>
                    <strong>@Html.LabelFor(m => m.Location, new { @class = "col-md-2" })</strong>
                </td>
                <td>
                    <strong>@Html.LabelFor(m => m.PointPerson, new { @class = "col-md-2" })</strong>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DropDownListFor(x => x.Provider.Id, new SelectList(Model.HfedProviders, "Id", "Name"), new { style = "width:140px" })
                    @Html.ValidationMessageFor(model => model.Provider.Id, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.DropDownListFor(x => x.Location.Id, new SelectList(Model.HfedLocations, "Id", "Name"), new { @id = "location_Id", style = "width:140px" })
                    @Html.ValidationMessageFor(model => model.Location.Id, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.DropDownListFor(x => x.PointPerson.Id, new SelectList(Model.HfedStaffs, "Id", "FullName"))
                    @Html.ValidationMessageFor(model => model.PointPerson.Id, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td><strong>Driver</strong></td>
                <td><strong>Households</strong></td>
                <td><strong>Note</strong></td>
                @*<td>Volunteer Hours</td>*@
            </tr>
            <tr>
                <td>
                    @Html.DropDownListFor(x => x.Driver.Id, new SelectList(Model.HfedDrivers, "Id", "FullName"), " Nobody Yet")
                    @Html.ValidationMessageFor(model => model.Driver.Id, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Households, new { onclick = "$(this).select();", style = "width:30px" })
                    @Html.ValidationMessageFor(model => model.Households, "", new { @class = "text-danger" })

                </td>

                <td>
                    @Html.EditorFor(model => model.ScheduleNote, new { htmlAttributes = new { @class = "form-control", style = "width:200px" } })
                    @Html.ValidationMessageFor(model => model.ScheduleNote, "", new { @class = "text-danger" })
                </td>
                @*<td>
                    @Html.EditorFor(model => model.VolunteerHours)
                    @Html.ValidationMessageFor(model => model.VolunteerHours, "", new { @class = "text-danger" })
                </td>*@
            </tr>
        </table>

        <table>
            <tr>
                <td><strong>Clients</strong></td>
            </tr>
            <tr>
                <td>
                    @Html.ListBoxFor(model => model.HfedClientsArray,
                        new MultiSelectList(Model.HfedClients, "Id", "FullName"),
                       new {Id = "clientsDDL" })
                </td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                @*<td style="text-align: right"><strong>I Approve This Run</strong></td>
                <td>
                    @Html.EditorFor(model => model.Approved)
                </td>*@
            <tr>
            <tr>
                <td colspan="2" style="color:red">
                    @Model.ErrorMessage
                </td>
            </tr>
        </table>
    </div>  

        <br />
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Save Changes" class="btn" style="background-color: aqua; font-weight:bold"/>
                </div>
            </div>
        }
    <br />
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

<script type="text/javascript">
    $(document).ready(function () {
        $('input[type=datetime]').datepicker({
            dateFormat: "mm/dd/yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "-5:+1"
        });
    });
</script>

<script>
    $(function () {
        $("#clientsDDL").chosen({ width: "150px" });
    });
</script>    

<script type="text/javascript">
    $("#location_Id").change(LoadClients);
</script>   

MVC5-Seneca/Views/HfedSchedules/Index.cshtml
@using System.Web.Mvc.Html
@model IEnumerable<MVC5_Seneca.EntityModels.HfedSchedule>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/chosen.jquery.min.js"></script>
    <link href="~/Content/chosen.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/themes/base/jquery-ui.min.css" /> @*// for date-picker*@
    @*Put page javascript in a separate .js file where breaks can be set during debugging:*@
    <script src="@Url.Content("/Scripts/HfedFunctions.js")"></script>
    </head>
<body>
<h3>
    HFED Delivery Schedule
</h3> 
<table class="table">
    <tr>
        <td><strong>Starting Date </strong></td>
        <td>@Html.TextBox("Starting Date", @Session["StartDate"].ToString(),
                new { id = "StartDate", style = "width: 75px;" })
            <span style="color:darkmagenta">&#8592;Click to change</span></td> @*Html left-arrow*@
        <td><strong>  Ending Date </strong></td>
        <td>@Html.TextBox("Ending Date", @Session["EndDate"].ToString(),
                new { id = "EndDate", style = "width: 75px;" })
            <span style="color:darkmagenta">&#8592;Click to change</span></td> @*Html left-arrow*@
        <td>@Html.ActionLink(" Previous Month", "MonthPrevious")</td>
        <td>@Html.ActionLink(" Next Month", "MonthNext")</td>              
    </tr>
</table>
<p>
    @Html.ActionLink("Create New Food Run", "Create")
</p>
<table>
    <tr>
        <th></th><th></th><th></th><th></th><th></th><th></th>
        <th>Point</th>
        <th>Number of</th>
        <th>Selected</th>
    </tr>
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            Provider
        </th>
        <th>
            Drop Off
        </th>
        <th>
            Driver
        </th>
        <th>
            PickUp
        </th>
        <th>
            Person
        </th>
        <th>
            Households
        </th>
        <th>
            Clients
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScheduleNote)
        </th>
        @*<th>
            <strong>Approved</strong>
        </th>*@
        @*<th>
            Vol Hrs.
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FormattedDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FormattedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Provider.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location.Name)
        </td>
        <td>
            @*Use ScheduleNote as dummy string for display-only DDL*@
            @*@Html.DropDownListFor(modelitem => item.ScheduleNote, item.SelectedHfedDrivers)*@
            @if (item.Driver != null)
            {
                @Html.DisplayFor(modelitem => item.Driver.FirstName)
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PickUpTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PointPerson.FirstName)
        </td>
        <td style="text-align:center">
            @Html.DisplayFor(modelItem => item.Households)
        </td>  
        <td>
            @*Use ScheduleNote as dummy string for display-only DDL*@
            @Html.DropDownListFor(modelitem => item.ScheduleNote, item.SelectedHfedClients)
            @Html.DisplayFor(modelitem => item.ClientsTotal)
        </td>
        <td title=@item.NoteToolTip> @*The length of the tool tip message depends on the browser.*@
            @Html.DisplayFor(modelItem => item.ScheduleNote)
        </td>
        @*<td style="text-align:center">
            @Html.DisplayFor(modelItem => item.Approved)
        </td>*@
        @*<td>
            @Html.DisplayFor(modelItem => item.VolunteerHours)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
    }
</table>
<br/>
<table>
    <tr>
        <td>
            @Html.ActionLink("Create Excel File", "CreateExcel")
        </td>
    </tr>
    @if (User.IsInRole("Administrator") || User.IsInRole("HfedCoordinator"))
    {
        <tr>
            <td>
                @Html.ActionLink("Duplicate Current Schedule Into Next Month", "Duplicate")
            </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Email Staff 2 Weeks Before Month - Request Schedules", "EmailStaffAsk", "HfedEmail")
            </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Email Schedule to All Drivers - Ask for Availability", "EmailDriversAsk","HfedEmail")
            </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Email Schedule to All Drivers - Show Drivers", "EmailDriversShow","HfedEmail")
            </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Email 2-day Reminder to All Scheduled Drivers & Staff", "EmailReminder", "HfedEmail")
            </td>
        </tr>
    }
</table>

<br/>
<table>
    <tr>
        <td>
            @Html.ActionLink("Return to Dashboard", "ReturnToHfedDashboard", new {})
        </td>
    </tr>
</table>
</body>
</html>
 
<script>
    $(function () {
        $("#StartDate").datepicker(); 
    });
</script>
<script type="text/javascript">
    $("#StartDate").change(function () {
        UpdateHfedStartDate($('#StartDate').val());          
    });                      
</script>
<script>
    $(function () {
        $("#EndDate").datepicker();
    });
</script>
<script type="text/javascript">
    $("#EndDate").change(function () {
        UpdateHfedEndDate($('#EndDate').val());
        //sessionStorage.setItem("StartDate", $('#EndDate').val());
    });                      
</script>